-- this script must be run as root user, e.g. # mysql -u root -p or use PHPMyAdmin
-- tables are generated by JPA/Eclipselink.
CREATE USER 'bfh'@'localhost' IDENTIFIED BY 'bfh';
CREATE DATABASE bfh;
GRANT ALL PRIVILEGES ON bfh.* TO 'bfh'@'localhost';